terminal:
  colorScheme:
    name: Batman
    foreground: '#6f6f6f'
    background: '#1b1d1e'
    cursor: '#fcef0c'
    colors:
      - '#1b1d1e'
      - '#e6dc44'
      - '#c8be46'
      - '#f4fd22'
      - '#737174'
      - '#747271'
      - '#62605f'
      - '#c6c5bf'
      - '#505354'
      - '#fff78e'
      - '#fff27d'
      - '#feed6c'
      - '#919495'
      - '#9a9a9d'
      - '#a3a3a6'
      - '#dadbd6'
  environment: {}
  profile: git-bash
  workingDirectory: 'D:\Dev'
  autoOpen: false
  recoverTabs: true
  profiles:
    - name: VeoxDev
      shell: git-bash
      sessionOptions:
        command: 'C:\Program Files\Git\bin\bash.exe'
        args:
          - '--login'
          - '-i'
        env:
          TERM: cygwin
        runAsAdministrator: true
        cwd: 'D:\dev\veox'
hotkeys:
  shell: {}
  profile:
    veoxdev:
      - - Ctrl-Shift-L
  toggle-window:
    - - Ctrl-Enter
serial: {}
ssh:
  connections:
    - name: IntelNuc
      group: null
      host: 192.168.0.166
      port: 22
      user: borja
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - diffie-hellman-group18-sha512
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-ed25519
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - ssh-rsa
      scripts: []
appearance:
  frame: thin
  dock: 'off'
  theme: Compact
  opacity: 1
  vibrancyType: fluent
  css: '/* * { color: blue !important; } */'
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []

